---
application:
  name: "blog-strapi"
  project: "BlogStrapi"
  organization: "QoveryCommunity"
databases:
- type: postgresql
  name: psql
  version: 12
routers:
- name: "main-blog-strapi"
  routes:
  - application_name: "blog-strapi"
    paths:
    - "/*"
